/*
  # Create Behavior Tracking System

  ## Overview
  This migration creates a comprehensive system for tracking client behaviors,
  identifying patterns, and generating insights to support coaching effectiveness.

  ## 1. New Tables
  
  ### `behavior_categories`
  - `id` (uuid, primary key)
  - `name` (text) - Category name (e.g., "Communication", "Emotional Response")
  - `description` (text) - Category description
  - `color` (text) - Color for visualization
  - `icon` (text) - Icon identifier
  - `created_at` (timestamptz)
  
  ### `behavior_observations`
  - `id` (uuid, primary key)
  - `coach_id` (uuid, foreign key to users)
  - `client_id` (uuid, foreign key to clients)
  - `session_id` (uuid, foreign key to sessions, nullable)
  - `category_id` (uuid, foreign key to behavior_categories)
  - `behavior_title` (text) - Short title of observed behavior
  - `behavior_description` (text) - Detailed description
  - `context` (text) - Context when behavior was observed
  - `intensity` (integer) - Intensity level 1-10
  - `emotional_state` (text) - Client's emotional state
  - `triggers` (text[]) - Identified triggers
  - `observed_at` (timestamptz) - When behavior was observed
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)
  
  ### `behavior_patterns`
  - `id` (uuid, primary key)
  - `coach_id` (uuid, foreign key to users)
  - `client_id` (uuid, foreign key to clients)
  - `pattern_type` (text) - Type: "recurring", "escalating", "improving", "cyclical"
  - `pattern_title` (text) - Pattern title
  - `pattern_description` (text) - Detailed pattern description
  - `frequency` (text) - How often it occurs
  - `related_behaviors` (uuid[]) - IDs of related observations
  - `identified_triggers` (text[]) - Common triggers
  - `confidence_score` (numeric) - AI confidence 0-1
  - `actionable_insights` (text[]) - Recommended actions
  - `status` (text) - "active", "monitoring", "resolved"
  - `identified_at` (timestamptz)
  - `last_occurrence` (timestamptz)
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)
  
  ### `behavior_insights`
  - `id` (uuid, primary key)
  - `coach_id` (uuid, foreign key to users)
  - `client_id` (uuid, foreign key to clients)
  - `pattern_id` (uuid, foreign key to behavior_patterns, nullable)
  - `insight_type` (text) - "strength", "challenge", "opportunity", "risk"
  - `title` (text) - Insight title
  - `description` (text) - Detailed insight
  - `recommendations` (text[]) - Action recommendations
  - `priority` (text) - "low", "medium", "high", "critical"
  - `ai_generated` (boolean) - Whether generated by AI
  - `visibility` (text) - "coach_only", "client_shared"
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)

  ## 2. Security
  - Enable RLS on all tables
  - Coaches can manage their own clients' behavior data
  - Clients can view shared insights only

  ## 3. Indexes
  - Index on client_id for fast queries
  - Index on observed_at for chronological retrieval
  - Index on pattern_type for filtering
*/

-- Create behavior_categories table
CREATE TABLE IF NOT EXISTS behavior_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL,
  color text DEFAULT '#3B82F6',
  icon text DEFAULT 'activity',
  created_at timestamptz DEFAULT now()
);

-- Create behavior_observations table
CREATE TABLE IF NOT EXISTS behavior_observations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  coach_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,
  session_id uuid REFERENCES sessions(id) ON DELETE SET NULL,
  category_id uuid REFERENCES behavior_categories(id) ON DELETE RESTRICT NOT NULL,
  behavior_title text NOT NULL,
  behavior_description text NOT NULL,
  context text DEFAULT '',
  intensity integer CHECK (intensity >= 1 AND intensity <= 10) DEFAULT 5,
  emotional_state text DEFAULT '',
  triggers text[] DEFAULT '{}',
  observed_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create behavior_patterns table
CREATE TABLE IF NOT EXISTS behavior_patterns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  coach_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,
  pattern_type text CHECK (pattern_type IN ('recurring', 'escalating', 'improving', 'cyclical')) NOT NULL,
  pattern_title text NOT NULL,
  pattern_description text NOT NULL,
  frequency text DEFAULT '',
  related_behaviors uuid[] DEFAULT '{}',
  identified_triggers text[] DEFAULT '{}',
  confidence_score numeric CHECK (confidence_score >= 0 AND confidence_score <= 1) DEFAULT 0.5,
  actionable_insights text[] DEFAULT '{}',
  status text CHECK (status IN ('active', 'monitoring', 'resolved')) DEFAULT 'active',
  identified_at timestamptz DEFAULT now(),
  last_occurrence timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create behavior_insights table
CREATE TABLE IF NOT EXISTS behavior_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  coach_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE NOT NULL,
  pattern_id uuid REFERENCES behavior_patterns(id) ON DELETE SET NULL,
  insight_type text CHECK (insight_type IN ('strength', 'challenge', 'opportunity', 'risk')) NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  recommendations text[] DEFAULT '{}',
  priority text CHECK (priority IN ('low', 'medium', 'high', 'critical')) DEFAULT 'medium',
  ai_generated boolean DEFAULT false,
  visibility text CHECK (visibility IN ('coach_only', 'client_shared')) DEFAULT 'coach_only',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_behavior_observations_client ON behavior_observations(client_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_observations_session ON behavior_observations(session_id);
CREATE INDEX IF NOT EXISTS idx_behavior_patterns_client ON behavior_patterns(client_id, status);
CREATE INDEX IF NOT EXISTS idx_behavior_patterns_type ON behavior_patterns(pattern_type);
CREATE INDEX IF NOT EXISTS idx_behavior_insights_client ON behavior_insights(client_id, priority);

-- Enable Row Level Security
ALTER TABLE behavior_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE behavior_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE behavior_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE behavior_insights ENABLE ROW LEVEL SECURITY;

-- RLS Policies for behavior_categories (public read for coaches)
CREATE POLICY "Anyone can view behavior categories"
  ON behavior_categories FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "System can manage behavior categories"
  ON behavior_categories FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- RLS Policies for behavior_observations
CREATE POLICY "Coaches can view their clients' observations"
  ON behavior_observations FOR SELECT
  TO authenticated
  USING (
    coach_id = auth.uid() OR
    client_id IN (SELECT id FROM clients WHERE coach_id = auth.uid())
  );

CREATE POLICY "Coaches can insert observations for their clients"
  ON behavior_observations FOR INSERT
  TO authenticated
  WITH CHECK (coach_id = auth.uid());

CREATE POLICY "Coaches can update their observations"
  ON behavior_observations FOR UPDATE
  TO authenticated
  USING (coach_id = auth.uid())
  WITH CHECK (coach_id = auth.uid());

CREATE POLICY "Coaches can delete their observations"
  ON behavior_observations FOR DELETE
  TO authenticated
  USING (coach_id = auth.uid());

-- RLS Policies for behavior_patterns
CREATE POLICY "Coaches can view their clients' patterns"
  ON behavior_patterns FOR SELECT
  TO authenticated
  USING (
    coach_id = auth.uid() OR
    client_id IN (SELECT id FROM clients WHERE coach_id = auth.uid())
  );

CREATE POLICY "Coaches can insert patterns for their clients"
  ON behavior_patterns FOR INSERT
  TO authenticated
  WITH CHECK (coach_id = auth.uid());

CREATE POLICY "Coaches can update their patterns"
  ON behavior_patterns FOR UPDATE
  TO authenticated
  USING (coach_id = auth.uid())
  WITH CHECK (coach_id = auth.uid());

CREATE POLICY "Coaches can delete their patterns"
  ON behavior_patterns FOR DELETE
  TO authenticated
  USING (coach_id = auth.uid());

-- RLS Policies for behavior_insights
CREATE POLICY "Users can view relevant insights"
  ON behavior_insights FOR SELECT
  TO authenticated
  USING (
    coach_id = auth.uid() OR 
    (client_id IN (SELECT id FROM clients WHERE coach_id = auth.uid()) AND visibility = 'client_shared')
  );

CREATE POLICY "Coaches can insert insights for their clients"
  ON behavior_insights FOR INSERT
  TO authenticated
  WITH CHECK (coach_id = auth.uid());

CREATE POLICY "Coaches can update their insights"
  ON behavior_insights FOR UPDATE
  TO authenticated
  USING (coach_id = auth.uid())
  WITH CHECK (coach_id = auth.uid());

CREATE POLICY "Coaches can delete their insights"
  ON behavior_insights FOR DELETE
  TO authenticated
  USING (coach_id = auth.uid());

-- Insert default behavior categories
INSERT INTO behavior_categories (name, description, color, icon) VALUES
  ('Communication', 'How the client expresses thoughts and listens', '#3B82F6', 'message-circle'),
  ('Emotional Response', 'Emotional reactions and regulation', '#EF4444', 'heart'),
  ('Decision Making', 'Approach to making choices and solving problems', '#8B5CF6', 'brain'),
  ('Motivation', 'Drive and commitment levels', '#F59E0B', 'zap'),
  ('Self-Awareness', 'Understanding of own thoughts and behaviors', '#10B981', 'eye'),
  ('Relationships', 'Interactions with others', '#EC4899', 'users'),
  ('Stress Response', 'How client handles pressure and challenges', '#F97316', 'alert-triangle'),
  ('Goal Orientation', 'Focus and commitment to objectives', '#06B6D4', 'target')
ON CONFLICT DO NOTHING;

-- Create updated_at trigger function if it doesn't exist
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add updated_at triggers
DROP TRIGGER IF EXISTS update_behavior_observations_updated_at ON behavior_observations;
CREATE TRIGGER update_behavior_observations_updated_at
  BEFORE UPDATE ON behavior_observations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_behavior_patterns_updated_at ON behavior_patterns;
CREATE TRIGGER update_behavior_patterns_updated_at
  BEFORE UPDATE ON behavior_patterns
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_behavior_insights_updated_at ON behavior_insights;
CREATE TRIGGER update_behavior_insights_updated_at
  BEFORE UPDATE ON behavior_insights
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();